### ISSUE TITLE
@formidable-webview/ersatz SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by leah-bluescape** [formidable-webview/ersatz#5]
We can reproduce this by simple use the RunKit function on npmjs https://npm.runkit.com/%40formidable-webview%2Fersatz

    Details:

    /Users/leahxia/Desktop/mobile_client/node_modules/@formidable-webview/ersatz/node_modules/node-fetch/src/index.js:9
    import http from 'http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@formidable-webview/ersatz/lib/commonjs/SourceLoader.tsx:3:1)

**Comment by jsamr** [comment]
It looks like `node-fetch` is an ESM module since version 3. ESM modules are supported by node and metro (React Native) bundler; not runkit apparently. If your issue happens in jest (where Ersatz usage is intended), make sure you are using babel metro preset. You `babel.config.js` file should look like this:

```js
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset'
  ],
  plugins: ['@babel/plugin-transform-react-jsx'],
};
```
